import { Restaurant, Category, Coupon, DeliveryAddress, Order } from './types';

export const CATEGORIES: Category[] = [
  {
    id: 'biryani',
    name: 'Biryani',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=300&auto=format&fit=crop&q=80',
    cuisineMatch: 'Biryani',
    badge: 'Popular',
  },
  {
    id: 'pizza',
    name: 'Pizza',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=300&auto=format&fit=crop&q=80',
    cuisineMatch: 'Pizza',
  },
  {
    id: 'burgers',
    name: 'Burgers',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=300&auto=format&fit=crop&q=80',
    cuisineMatch: 'Burgers',
    badge: 'Trending',
  },
  {
    id: 'north-indian',
    name: 'North Indian',
    image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=300&auto=format&fit=crop&q=80',
    cuisineMatch: 'North Indian',
  },
  {
    id: 'south-indian',
    name: 'South Indian',
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=300&auto=format&fit=crop&q=80',
    cuisineMatch: 'South Indian',
  },
  {
    id: 'chinese',
    name: 'Chinese',
    image: 'https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?w=300&auto=format&fit=crop&q=80',
    cuisineMatch: 'Chinese',
  },
  {
    id: 'rolls',
    name: 'Rolls & Wraps',
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=300&auto=format&fit=crop&q=80',
    cuisineMatch: 'Rolls',
  },
  {
    id: 'momos',
    name: 'Momos',
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=300&auto=format&fit=crop&q=80',
    cuisineMatch: 'Momos',
  },
  {
    id: 'desserts',
    name: 'Desserts',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=300&auto=format&fit=crop&q=80',
    cuisineMatch: 'Desserts',
  },
  {
    id: 'cakes',
    name: 'Cakes & Bakery',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=300&auto=format&fit=crop&q=80',
    cuisineMatch: 'Bakery',
  },
  {
    id: 'thali',
    name: 'Royal Thali',
    image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=300&auto=format&fit=crop&q=80',
    cuisineMatch: 'Thali',
    badge: 'Value',
  },
  {
    id: 'healthy',
    name: 'Healthy Bowls',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=300&auto=format&fit=crop&q=80',
    cuisineMatch: 'Healthy Food',
  },
  {
    id: 'street-food',
    name: 'Street Chaat',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=300&auto=format&fit=crop&q=80',
    cuisineMatch: 'Street Food',
  },
  {
    id: 'beverages',
    name: 'Chai & Shakes',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=300&auto=format&fit=crop&q=80',
    cuisineMatch: 'Beverages',
  },
];

export const PROMO_BANNERS = [
  {
    id: 'banner-1',
    title: '50% OFF on First Order',
    subtitle: 'Use code WELCOME50 • Min. order ₹199',
    code: 'WELCOME50',
    tag: 'FIRST BITE SPECIAL',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=80',
    color: 'from-amber-600 to-orange-700',
  },
  {
    id: 'banner-2',
    title: 'Free Delivery Weekend',
    subtitle: 'Zero delivery fee on all top-rated restaurants',
    code: 'FREEDEL',
    tag: 'LIMITED TIME',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=80',
    color: 'from-rose-600 to-red-700',
  },
  {
    id: 'banner-3',
    title: 'Flat ₹150 OFF Gourmet Feast',
    subtitle: 'Indulge in authentic regional delicacies above ₹499',
    code: 'FEAST150',
    tag: 'GOURMET CURATION',
    image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=800&auto=format&fit=crop&q=80',
    color: 'from-emerald-700 to-teal-800',
  },
];

export const CRAVINGS = [
  {
    name: 'Dum Biryani',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400&auto=format&fit=crop&q=80',
    cuisine: 'Biryani',
    count: '34+ Outlets',
  },
  {
    name: 'Artisan Pizza',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&auto=format&fit=crop&q=80',
    cuisine: 'Pizza',
    count: '28+ Outlets',
  },
  {
    name: 'Smash Burgers',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&auto=format&fit=crop&q=80',
    cuisine: 'Burgers',
    count: '22+ Outlets',
  },
  {
    name: 'Butter Chicken & Naan',
    image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=400&auto=format&fit=crop&q=80',
    cuisine: 'North Indian',
    count: '45+ Outlets',
  },
  {
    name: 'Crispy Dosas',
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=400&auto=format&fit=crop&q=80',
    cuisine: 'South Indian',
    count: '19+ Outlets',
  },
  {
    name: 'Steamed Momos',
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=400&auto=format&fit=crop&q=80',
    cuisine: 'Momos',
    count: '15+ Outlets',
  },
  {
    name: 'Kathi Rolls',
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=400&auto=format&fit=crop&q=80',
    cuisine: 'Rolls',
    count: '26+ Outlets',
  },
  {
    name: 'Gulab Jamun & Sweets',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=400&auto=format&fit=crop&q=80',
    cuisine: 'Desserts',
    count: '18+ Outlets',
  },
];

export const COUPONS: Coupon[] = [
  {
    code: 'WELCOME50',
    title: '50% OFF up to ₹100',
    description: 'Valid on your first order. Minimum bill value ₹199.',
    discountType: 'percentage',
    discountValue: 50,
    maxDiscount: 100,
    minOrderValue: 199,
    validUntil: '31 Aug 2026',
  },
  {
    code: 'FEAST150',
    title: 'Flat ₹150 OFF',
    description: 'Enjoy delicious family feasts on orders above ₹499.',
    discountType: 'flat',
    discountValue: 150,
    minOrderValue: 499,
    validUntil: '15 Sep 2026',
  },
  {
    code: 'FREEDEL',
    title: 'Free Delivery',
    description: 'Save 100% on delivery charges for orders above ₹299.',
    discountType: 'flat',
    discountValue: 45, // equivalent delivery waiver
    minOrderValue: 299,
    validUntil: 'Ongoing',
  },
  {
    code: 'ZAIKAPARTY',
    title: 'Flat 30% OFF up to ₹250',
    description: 'Celebrate group meals & weekend binges on orders above ₹699.',
    discountType: 'percentage',
    discountValue: 30,
    maxDiscount: 250,
    minOrderValue: 699,
    validUntil: '30 Sep 2026',
  },
];

export const RESTAURANTS: Restaurant[] = [
  {
    id: 'rest-1',
    name: 'Nawabi Dum Biryani House',
    tagline: 'Authentic Kachchi Hyderabadi Dum Biryani & Kebabs',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=1200&auto=format&fit=crop&q=80',
    cuisines: ['Biryani', 'Mughlai', 'North Indian', 'Kebabs'],
    rating: 4.6,
    ratingCount: '4.8k+ ratings',
    deliveryTimeMin: 25,
    deliveryTimeMax: 30,
    distanceKm: 2.1,
    priceForTwo: 350,
    offer: '50% OFF up to ₹100',
    offerCode: 'WELCOME50',
    isPureVeg: false,
    isTopRated: true,
    isFeatured: true,
    address: 'Plot 42, 80 Feet Road, 4th Block, Koramangala',
    locality: 'Koramangala',
    city: 'Bengaluru',
    categories: ['Recommended', 'Dum Biryani Specials', 'Starters & Kebabs', 'Mughlai Curries', 'Breads', 'Desserts', 'Beverages'],
    menu: [
      {
        id: 'item-101',
        restaurantId: 'rest-1',
        name: 'Hyderabadi Chicken Dum Biryani',
        description: 'Fragrant long-grain basmati rice cooked on slow coal dum with tender marinated chicken pieces, infused with saffron, mint, and secret royal spices. Served with Mirchi ka Salan & Raita.',
        price: 299,
        originalPrice: 349,
        image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=500&auto=format&fit=crop&q=80',
        category: 'Dum Biryani Specials',
        vegType: 'non-veg',
        rating: 4.8,
        ratingCount: 2310,
        isBestseller: true,
        isSpicy: true,
        customizationGroups: [
          {
            id: 'portion',
            title: 'Select Portion Size',
            type: 'radio',
            options: [
              { id: 'regular', name: 'Regular (Serves 1 - 2 Pcs Chicken)', price: 0 },
              { id: 'jumbo', name: 'Jumbo Pack (Serves 2 - 4 Pcs Chicken + 2 Boiled Eggs)', price: 180 },
            ],
          },
          {
            id: 'spice',
            title: 'Choose Spice Level',
            type: 'radio',
            options: [
              { id: 'medium', name: 'Medium Spicy (Original Nizami)', price: 0 },
              { id: 'extra', name: 'Spicy & Fiery Andhra Style', price: 0 },
            ],
          },
          {
            id: 'addons',
            title: 'Royal Add-ons',
            type: 'checkbox',
            options: [
              { id: 'egg', name: 'Extra Boiled Egg (1 pc)', price: 25 },
              { id: 'salan', name: 'Extra Mirchi Ka Salan (200ml)', price: 40 },
              { id: 'raita', name: 'Thick Burani Garlic Raita', price: 35 },
            ],
          },
        ],
      },
      {
        id: 'item-102',
        restaurantId: 'rest-1',
        name: 'Nizami Mutton Dum Biryani',
        description: 'Tender prime baby lamb cutlets slow-cooked with basmati rice, browned onions, kewra water, and aromatic whole spices. A royal feast.',
        price: 429,
        originalPrice: 489,
        image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=500&auto=format&fit=crop&q=80',
        category: 'Dum Biryani Specials',
        vegType: 'non-veg',
        rating: 4.7,
        ratingCount: 1420,
        isBestseller: true,
        isSpicy: true,
      },
      {
        id: 'item-103',
        restaurantId: 'rest-1',
        name: 'Royal Shahi Paneer Biryani',
        description: 'Fresh malai paneer cubes marinated in yogurt and tikka spices, layered with saffron basmati rice and roasted cashews.',
        price: 269,
        originalPrice: 310,
        image: 'https://images.unsplash.com/photo-1642821373181-696a54913e9a?w=500&auto=format&fit=crop&q=80',
        category: 'Dum Biryani Specials',
        vegType: 'veg',
        rating: 4.5,
        ratingCount: 980,
      },
      {
        id: 'item-104',
        restaurantId: 'rest-1',
        name: 'Murgh Malai Tikka (6 Pcs)',
        description: 'Creamy boneless chicken morsels marinated in fresh cream, cream cheese, cardamom, and green chilies, roasted in clay tandoor.',
        price: 320,
        image: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=500&auto=format&fit=crop&q=80',
        category: 'Starters & Kebabs',
        vegType: 'non-veg',
        rating: 4.6,
        ratingCount: 840,
        isBestseller: true,
      },
      {
        id: 'item-105',
        restaurantId: 'rest-1',
        name: 'Galouti Kebab with Mini Parathas',
        description: 'Melt-in-mouth smoked lamb patties spiced with 32 secret Lucknowi herbs, served with 2 Ulte Tawe ke Parathe.',
        price: 380,
        image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=500&auto=format&fit=crop&q=80',
        category: 'Starters & Kebabs',
        vegType: 'non-veg',
        rating: 4.8,
        ratingCount: 650,
      },
      {
        id: 'item-106',
        restaurantId: 'rest-1',
        name: 'Shahi Tukda with Rabri',
        description: 'Crispy fried bread steeped in saffron-cardamom sugar syrup, topped with thick condensed malai rabri and pistachios.',
        price: 149,
        image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=500&auto=format&fit=crop&q=80',
        category: 'Desserts',
        vegType: 'veg',
        rating: 4.9,
        ratingCount: 1120,
        isBestseller: true,
      },
    ],
  },
  {
    id: 'rest-2',
    name: 'Punjab Grill House',
    tagline: 'Rich North Indian Curries, Tandoori Platters & Butter Naan',
    image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=600&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200&auto=format&fit=crop&q=80',
    cuisines: ['North Indian', 'Punjabi', 'Tandoor', 'Breads'],
    rating: 4.7,
    ratingCount: '3.2k+ ratings',
    deliveryTimeMin: 30,
    deliveryTimeMax: 35,
    distanceKm: 3.4,
    priceForTwo: 450,
    offer: 'Flat ₹150 OFF above ₹499',
    offerCode: 'FEAST150',
    isPureVeg: false,
    isTopRated: true,
    address: '12th Main Road, HAL 2nd Stage, Indiranagar',
    locality: 'Indiranagar',
    city: 'Bengaluru',
    categories: ['Recommended', 'Tandoori Starters', 'Rich Gravies & Curries', 'Dal & Rice', 'Tandoori Breads', 'Desserts'],
    menu: [
      {
        id: 'item-201',
        restaurantId: 'rest-2',
        name: 'Old Delhi Butter Chicken (Boneless)',
        description: 'Tender tandoor-roasted chicken simmered in rich, velvety tomato butter gravy, finished with fresh fenugreek (kasuri methi) and cream.',
        price: 349,
        originalPrice: 399,
        image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=500&auto=format&fit=crop&q=80',
        category: 'Rich Gravies & Curries',
        vegType: 'non-veg',
        rating: 4.9,
        ratingCount: 3100,
        isBestseller: true,
        customizationGroups: [
          {
            id: 'portion',
            title: 'Choose Gravy Style',
            type: 'radio',
            options: [
              { id: 'creamy', name: 'Classic Sweet & Tangy Creamy', price: 0 },
              { id: 'spicy', name: 'Spicy Dhaba Style Cut Gravy', price: 0 },
            ],
          },
          {
            id: 'breads',
            title: 'Add Fresh Breads',
            type: 'checkbox',
            options: [
              { id: 'garlicnaan', name: 'Butter Garlic Naan (1 Pc)', price: 55 },
              { id: 'lachhaparatha', name: 'Crispy Laccha Paratha (1 Pc)', price: 45 },
            ],
          },
        ],
      },
      {
        id: 'item-202',
        restaurantId: 'rest-2',
        name: 'Dal Makhani - 24hr Slow Simmered',
        description: 'Whole black lentils, kidney beans cooked overnight with fresh cream, white butter, and gentle ground spices in traditional clay pot.',
        price: 259,
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=500&auto=format&fit=crop&q=80',
        category: 'Dal & Rice',
        vegType: 'veg',
        rating: 4.8,
        ratingCount: 2200,
        isBestseller: true,
      },
      {
        id: 'item-203',
        restaurantId: 'rest-2',
        name: 'Paneer Tikka Masala',
        description: 'Char-grilled cubes of cottage cheese with bell peppers and onions in a spiced onion-tomato masala gravy.',
        price: 299,
        image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=500&auto=format&fit=crop&q=80',
        category: 'Rich Gravies & Curries',
        vegType: 'veg',
        rating: 4.6,
        ratingCount: 1200,
      },
      {
        id: 'item-204',
        restaurantId: 'rest-2',
        name: 'Amritsari Kulcha with Chole',
        description: 'Stuffed spiced potato and onion tandoori flatbread topped with coriander & butter, served with pindi chole and tamarind dip.',
        price: 219,
        image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=500&auto=format&fit=crop&q=80',
        category: 'Recommended',
        vegType: 'veg',
        rating: 4.7,
        ratingCount: 890,
      },
      {
        id: 'item-205',
        restaurantId: 'rest-2',
        name: 'Garlic Butter Naan (2 Pcs)',
        description: 'Refined flour bread cooked in tandoor, slathered with chopped garlic, fresh coriander, and melted butter.',
        price: 99,
        image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&auto=format&fit=crop&q=80',
        category: 'Tandoori Breads',
        vegType: 'veg',
        rating: 4.8,
        ratingCount: 1540,
      },
      {
        id: 'item-206',
        restaurantId: 'rest-2',
        name: 'Warm Gulab Jamun with Pista (2 Pcs)',
        description: 'Soft golden fried khoya dumplings soaked in rose cardamom sugar syrup, served piping hot with sliced pistachios.',
        price: 89,
        image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=500&auto=format&fit=crop&q=80',
        category: 'Desserts',
        vegType: 'veg',
        rating: 4.9,
        ratingCount: 1800,
      },
    ],
  },
  {
    id: 'rest-3',
    name: 'Dosa Factory & South Express',
    tagline: 'Crispy Ghee Podi Dosas, Steamed Idlis & Filter Coffee',
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=600&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=1200&auto=format&fit=crop&q=80',
    cuisines: ['South Indian', 'Dosa', 'Pure Veg', 'Breakfast'],
    rating: 4.8,
    ratingCount: '5.1k+ ratings',
    deliveryTimeMin: 18,
    deliveryTimeMax: 22,
    distanceKm: 1.2,
    priceForTwo: 200,
    offer: 'Free Delivery above ₹199',
    offerCode: 'FREEDEL',
    isPureVeg: true,
    isTopRated: true,
    isFeatured: true,
    address: 'Near Sony World Signal, 100 Feet Road, Koramangala',
    locality: 'Koramangala',
    city: 'Bengaluru',
    categories: ['Recommended', 'Signature Dosas', 'Idli & Vada', 'Rice Meals', 'Beverages'],
    menu: [
      {
        id: 'item-301',
        restaurantId: 'rest-3',
        name: 'Ghee Roast Mysore Masala Dosa',
        description: 'Crispy golden crepe smeared with authentic red garlic chutney, filled with spiced aloo masala, roasted in pure desi ghee. Served with 3 chutneys & drumstick sambar.',
        price: 145,
        originalPrice: 170,
        image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=500&auto=format&fit=crop&q=80',
        category: 'Signature Dosas',
        vegType: 'veg',
        rating: 4.9,
        ratingCount: 3890,
        isBestseller: true,
        customizationGroups: [
          {
            id: 'extra_chutney',
            title: 'Chutney Preference',
            type: 'checkbox',
            options: [
              { id: 'coconut', name: 'Extra Coconut Chutney', price: 15 },
              { id: 'podi', name: 'Extra Gunpowder Podi with Ghee', price: 25 },
            ],
          },
        ],
      },
      {
        id: 'item-302',
        restaurantId: 'rest-3',
        name: 'Gunpowder Podi Idli (2 Pcs)',
        description: 'Mini button idlis tossed in spicy roasted lentil gunpowder, curry leaves, mustard seeds, and generous melting ghee.',
        price: 110,
        image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=500&auto=format&fit=crop&q=80',
        category: 'Idli & Vada',
        vegType: 'veg',
        rating: 4.8,
        ratingCount: 1980,
        isBestseller: true,
      },
      {
        id: 'item-303',
        restaurantId: 'rest-3',
        name: 'Crispy Medu Vada (2 Pcs)',
        description: 'Golden fried lentil donuts with crispy crust and fluffy interior, infused with peppercorn, cumin, and fresh coconut chunks.',
        price: 95,
        image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&auto=format&fit=crop&q=80',
        category: 'Idli & Vada',
        vegType: 'veg',
        rating: 4.7,
        ratingCount: 1420,
      },
      {
        id: 'item-304',
        restaurantId: 'rest-3',
        name: 'Traditional South Indian Filter Coffee',
        description: 'Freshly decocted chicory blend coffee frothed with thick whole milk in traditional brass dabarah.',
        price: 65,
        image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop&q=80',
        category: 'Beverages',
        vegType: 'veg',
        rating: 4.9,
        ratingCount: 2900,
        isBestseller: true,
      },
      {
        id: 'item-305',
        restaurantId: 'rest-3',
        name: 'Bisi Bele Bath with Boondi',
        description: 'Karnataka special hot lentil rice cooked with assorted vegetables, tamarind, nutmeg, and aromatic bisi bele masala. Topped with crunchy kara boondi.',
        price: 140,
        image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=500&auto=format&fit=crop&q=80',
        category: 'Rice Meals',
        vegType: 'veg',
        rating: 4.6,
        ratingCount: 750,
      },
    ],
  },
  {
    id: 'rest-4',
    name: 'Artisan Crust Pizza Co.',
    tagline: 'Wood-fired Sourdough Pizzas, Garlic Knots & Pasta',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1579751626657-72bc17010498?w=1200&auto=format&fit=crop&q=80',
    cuisines: ['Pizza', 'Italian', 'Pasta', 'Fast Food'],
    rating: 4.5,
    ratingCount: '2.9k+ ratings',
    deliveryTimeMin: 28,
    deliveryTimeMax: 33,
    distanceKm: 2.8,
    priceForTwo: 500,
    offer: '30% OFF up to ₹250',
    offerCode: 'ZAIKAPARTY',
    isPureVeg: false,
    isTopRated: false,
    isFeatured: true,
    address: '5th Cross, 6th Block, Koramangala',
    locality: 'Koramangala',
    city: 'Bengaluru',
    categories: ['Recommended', 'Artisan Sourdough Pizzas', 'Signature Pastas', 'Starters & Sides', 'Beverages'],
    menu: [
      {
        id: 'item-401',
        restaurantId: 'rest-4',
        name: 'Smoked Chicken & Peri Peri Pizza (11 Inch)',
        description: 'Slow-fermented sourdough crust topped with San Marzano tomato sauce, smoked paprika chicken chunks, fiery peri-peri drizzle, mozzarella & fresh basil.',
        price: 449,
        originalPrice: 520,
        image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=500&auto=format&fit=crop&q=80',
        category: 'Artisan Sourdough Pizzas',
        vegType: 'non-veg',
        rating: 4.8,
        ratingCount: 1680,
        isBestseller: true,
        customizationGroups: [
          {
            id: 'crust',
            title: 'Choose Crust Style',
            type: 'radio',
            options: [
              { id: 'sourdough', name: 'Classic Neapolitan Sourdough', price: 0 },
              { id: 'cheeseburst', name: 'Cheese Burst Crust', price: 80 },
            ],
          },
          {
            id: 'cheese_addon',
            title: 'Extra Cheese & Toppings',
            type: 'checkbox',
            options: [
              { id: 'extra_cheese', name: 'Extra Mozzarella & Parmesan', price: 60 },
              { id: 'jalapenos', name: 'Spicy Pickled Jalapenos', price: 35 },
              { id: 'olives', name: 'Black Kalamata Olives', price: 40 },
            ],
          },
        ],
      },
      {
        id: 'item-402',
        restaurantId: 'rest-4',
        name: 'Four Cheese Margherita Truffle Pizza',
        description: 'Fresh buffalo mozzarella, aged parmesan, gorgonzola, smoked provolone with a whisper of white truffle oil and fresh garden basil.',
        price: 389,
        image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=500&auto=format&fit=crop&q=80',
        category: 'Artisan Sourdough Pizzas',
        vegType: 'veg',
        rating: 4.7,
        ratingCount: 1240,
        isBestseller: true,
      },
      {
        id: 'item-403',
        restaurantId: 'rest-4',
        name: 'Creamy Alfredo Penne with Roasted Garlic',
        description: 'Al dente penne pasta coated in rich parmesan garlic cream sauce with sauteed broccoli, sun-dried tomatoes, and fresh herbs.',
        price: 299,
        image: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281086?w=500&auto=format&fit=crop&q=80',
        category: 'Signature Pastas',
        vegType: 'veg',
        rating: 4.6,
        ratingCount: 890,
      },
      {
        id: 'item-404',
        restaurantId: 'rest-4',
        name: 'Cheesy Garlic Bread Sticks with Marinara',
        description: 'Baked bread sticks brushed with roasted garlic herb butter, filled with gooey mozzarella, served with spicy tomato marinara dip.',
        price: 169,
        image: 'https://images.unsplash.com/photo-1573821663912-569905455b1c?w=500&auto=format&fit=crop&q=80',
        category: 'Starters & Sides',
        vegType: 'veg',
        rating: 4.7,
        ratingCount: 1540,
      },
    ],
  },
  {
    id: 'rest-5',
    name: 'Dragon Wok Indo-Chinese',
    tagline: 'Sizzling Hakka Noodles, Manchurian Bowls & Momos',
    image: 'https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?w=600&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=1200&auto=format&fit=crop&q=80',
    cuisines: ['Chinese', 'Asian', 'Momos', 'Noodles'],
    rating: 4.4,
    ratingCount: '2.1k+ ratings',
    deliveryTimeMin: 22,
    deliveryTimeMax: 27,
    distanceKm: 1.8,
    priceForTwo: 300,
    offer: '50% OFF up to ₹100',
    offerCode: 'WELCOME50',
    isPureVeg: false,
    isTopRated: false,
    address: '8th Main, 3rd Stage, BTM Layout',
    locality: 'BTM Layout',
    city: 'Bengaluru',
    categories: ['Recommended', 'Dimsums & Momos', 'Wok Starters', 'Noodles & Fried Rice', 'Combo Meals'],
    menu: [
      {
        id: 'item-501',
        restaurantId: 'rest-5',
        name: 'Steamed Chicken Darjeeling Momos (6 Pcs)',
        description: 'Thin-skinned juicy minced chicken dumplings seasoned with mountain herbs and spring onions. Served with hot red chili garlic chutney.',
        price: 169,
        originalPrice: 199,
        image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=500&auto=format&fit=crop&q=80',
        category: 'Dimsums & Momos',
        vegType: 'non-veg',
        rating: 4.8,
        ratingCount: 2100,
        isBestseller: true,
        isSpicy: true,
      },
      {
        id: 'item-502',
        restaurantId: 'rest-5',
        name: 'Chilli Chicken Dry (Chef Special)',
        description: 'Crispy fried chicken chunks wok-tossed with fresh ginger, garlic, green chilies, onions, and spicy dark soya sauce.',
        price: 259,
        image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=500&auto=format&fit=crop&q=80',
        category: 'Wok Starters',
        vegType: 'non-veg',
        rating: 4.7,
        ratingCount: 1650,
        isBestseller: true,
        isSpicy: true,
      },
      {
        id: 'item-503',
        restaurantId: 'rest-5',
        name: 'Veg Hakka Noodles with Manchurian Combo',
        description: 'Smoky wok-tossed noodles with shredded cabbage, carrots, bell peppers, paired with vegetable manchurian balls in luscious gravy.',
        price: 229,
        image: 'https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?w=500&auto=format&fit=crop&q=80',
        category: 'Combo Meals',
        vegType: 'veg',
        rating: 4.6,
        ratingCount: 1320,
      },
      {
        id: 'item-504',
        restaurantId: 'rest-5',
        name: 'Schezwan Egg Fried Rice',
        description: 'Fluffy jasmine rice tossed with scrambled eggs, scallions, and homemade fiery Sichuan pepper sauce.',
        price: 199,
        image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500&auto=format&fit=crop&q=80',
        category: 'Noodles & Fried Rice',
        vegType: 'egg',
        rating: 4.5,
        ratingCount: 940,
        isSpicy: true,
      },
    ],
  },
  {
    id: 'rest-6',
    name: 'Burger Craft & Shake Lab',
    tagline: 'Juicy Smash Burgers, Crispy Fries & Thick Milkshakes',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=1200&auto=format&fit=crop&q=80',
    cuisines: ['Burgers', 'American', 'Fast Food', 'Beverages'],
    rating: 4.6,
    ratingCount: '3.7k+ ratings',
    deliveryTimeMin: 20,
    deliveryTimeMax: 25,
    distanceKm: 1.5,
    priceForTwo: 350,
    offer: 'Flat ₹100 OFF',
    offerCode: 'WELCOME50',
    isPureVeg: false,
    isTopRated: true,
    address: 'Near Forum Mall, Hosur Road, Koramangala',
    locality: 'Koramangala',
    city: 'Bengaluru',
    categories: ['Recommended', 'Craft Burgers', 'Crispy Fries & Sides', 'Thick Milkshakes'],
    menu: [
      {
        id: 'item-601',
        restaurantId: 'rest-6',
        name: 'The Big Boss Double Smash Chicken Burger',
        description: 'Two crispy grilled chicken patties with double melted cheddar, caramelized onions, jalapeño relish, and secret truffle burger sauce in toasted brioche bun.',
        price: 269,
        originalPrice: 310,
        image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&auto=format&fit=crop&q=80',
        category: 'Craft Burgers',
        vegType: 'non-veg',
        rating: 4.9,
        ratingCount: 2890,
        isBestseller: true,
      },
      {
        id: 'item-602',
        restaurantId: 'rest-6',
        name: 'Crispy Paneer Makhani Crunch Burger',
        description: 'Crumb-fried cottage cheese patty layered with lettuce, mint mayo, crunchy onions, and a dash of buttery makhani sauce.',
        price: 219,
        image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=500&auto=format&fit=crop&q=80',
        category: 'Craft Burgers',
        vegType: 'veg',
        rating: 4.7,
        ratingCount: 1450,
      },
      {
        id: 'item-603',
        restaurantId: 'rest-6',
        name: 'Peri Peri Seasoned Crinkle Fries',
        description: 'Golden crunchy potato fries dusted with authentic African bird eye peri-peri seasoning. Served with cheese dip.',
        price: 119,
        image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?w=500&auto=format&fit=crop&q=80',
        category: 'Crispy Fries & Sides',
        vegType: 'veg',
        rating: 4.6,
        ratingCount: 1890,
      },
      {
        id: 'item-604',
        restaurantId: 'rest-6',
        name: 'Belgian Chocolate & Nutella Thick Shake',
        description: 'Rich creamy milkshake blended with authentic Belgian cocoa, Nutella swirl, and brownie crumble.',
        price: 179,
        image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=500&auto=format&fit=crop&q=80',
        category: 'Thick Milkshakes',
        vegType: 'veg',
        rating: 4.8,
        ratingCount: 1230,
        isBestseller: true,
      },
    ],
  },
  {
    id: 'rest-7',
    name: 'Kolkata Kathi Rolls & Chaat',
    tagline: 'Flaky Paratha Rolls, Mughlai Egg Rolls & Tangy Chaat',
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=600&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=1200&auto=format&fit=crop&q=80',
    cuisines: ['Rolls', 'Street Food', 'Snacks', 'Fast Food'],
    rating: 4.5,
    ratingCount: '1.9k+ ratings',
    deliveryTimeMin: 15,
    deliveryTimeMax: 20,
    distanceKm: 0.9,
    priceForTwo: 180,
    offer: 'Free Delivery above ₹149',
    offerCode: 'FREEDEL',
    isPureVeg: false,
    isTopRated: false,
    address: '60 Feet Road, 5th Block, Koramangala',
    locality: 'Koramangala',
    city: 'Bengaluru',
    categories: ['Recommended', 'Signature Kathi Rolls', 'Egg Rolls', 'Street Chaats', 'Beverages'],
    menu: [
      {
        id: 'item-701',
        restaurantId: 'rest-7',
        name: 'Double Chicken Double Egg Kathi Roll',
        description: 'Flaky laccha paratha cooked with two eggs, filled with tender spiced chicken tikka chunks, pickled sliced onions, green chilies, and a squeeze of fresh lime.',
        price: 179,
        originalPrice: 210,
        image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=500&auto=format&fit=crop&q=80',
        category: 'Signature Kathi Rolls',
        vegType: 'non-veg',
        rating: 4.8,
        ratingCount: 2400,
        isBestseller: true,
        isSpicy: true,
      },
      {
        id: 'item-702',
        restaurantId: 'rest-7',
        name: 'Paneer Tikka Roll with Mint Mayo',
        description: 'Marinated cottage cheese roasted with capsicum and wrapped in a crisp paratha with tangy pudina sauce.',
        price: 139,
        image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&auto=format&fit=crop&q=80',
        category: 'Signature Kathi Rolls',
        vegType: 'veg',
        rating: 4.6,
        ratingCount: 1100,
      },
      {
        id: 'item-703',
        restaurantId: 'rest-7',
        name: 'Dahi Puri & Papdi Chaat Medley',
        description: 'Crispy puffed puris stuffed with boiled potato mash, chilled sweet curd, tamarind chutney, and fragrant sev.',
        price: 99,
        image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&auto=format&fit=crop&q=80',
        category: 'Street Chaats',
        vegType: 'veg',
        rating: 4.7,
        ratingCount: 950,
      },
    ],
  },
  {
    id: 'rest-8',
    name: 'Sweet Bengal Confectionery',
    tagline: 'Pure Ghee Sweets, Soft Rasgulla & Fresh Pastries',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=1200&auto=format&fit=crop&q=80',
    cuisines: ['Desserts', 'Bakery', 'Sweets', 'Pure Veg'],
    rating: 4.9,
    ratingCount: '4.2k+ ratings',
    deliveryTimeMin: 15,
    deliveryTimeMax: 20,
    distanceKm: 1.4,
    priceForTwo: 220,
    offer: '20% OFF above ₹299',
    offerCode: 'WELCOME50',
    isPureVeg: true,
    isTopRated: true,
    address: 'Near Madivala Lake Road, BTM 1st Stage',
    locality: 'BTM Layout',
    city: 'Bengaluru',
    categories: ['Recommended', 'Traditional Sweets', 'Artisan Cakes & Pastries', 'Dry Fruit Boxes'],
    menu: [
      {
        id: 'item-801',
        restaurantId: 'rest-8',
        name: 'Spongy Bengali Rasgulla (4 Pcs)',
        description: 'Fresh cow milk chenna dumplings simmered in crystal clear rose-flavored light sugar syrup. Melt in the mouth delicacy.',
        price: 110,
        image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=500&auto=format&fit=crop&q=80',
        category: 'Traditional Sweets',
        vegType: 'veg',
        rating: 4.9,
        ratingCount: 3100,
        isBestseller: true,
      },
      {
        id: 'item-802',
        restaurantId: 'rest-8',
        name: 'Dutch Chocolate Truffle Pastry (1 Pc)',
        description: 'Decadent dark chocolate sponge layered with rich Belgian chocolate ganache and chocolate shavings.',
        price: 135,
        image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500&auto=format&fit=crop&q=80',
        category: 'Artisan Cakes & Pastries',
        vegType: 'veg',
        rating: 4.8,
        ratingCount: 1800,
        isBestseller: true,
      },
      {
        id: 'item-803',
        restaurantId: 'rest-8',
        name: 'Kaju Katli Silver Vark Gift Box (250g)',
        description: 'Diamond-shaped traditional Indian sweet made with premium cashew nuts and pure sugar syrup, finished with edible silver foil.',
        price: 290,
        image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=500&auto=format&fit=crop&q=80',
        category: 'Dry Fruit Boxes',
        vegType: 'veg',
        rating: 4.9,
        ratingCount: 2200,
      },
    ],
  },
];

export const SAMPLE_ADDRESSES: DeliveryAddress[] = [
  {
    id: 'addr-1',
    type: 'Home',
    label: 'Home',
    street: 'Flat 402, Sai Residency, 4th Cross',
    area: 'Koramangala 5th Block',
    city: 'Bengaluru',
    pincode: '560095',
    phone: '+91 98765 43210',
    isDefault: true,
  },
  {
    id: 'addr-2',
    type: 'Work',
    label: 'Office - WeWork Galaxy',
    street: '43 Residency Road, Shanthala Nagar',
    area: 'Ashok Nagar',
    city: 'Bengaluru',
    pincode: '560025',
    phone: '+91 98765 43210',
  },
  {
    id: 'addr-3',
    type: 'Other',
    label: "Friend's Place",
    street: '12, 100 Feet Road, HAL 2nd Stage',
    area: 'Indiranagar',
    city: 'Bengaluru',
    pincode: '560038',
    phone: '+91 98765 43210',
  },
];

export const INITIAL_PAST_ORDERS: Order[] = [
  {
    id: 'order-1001',
    orderNumber: 'ZK-98421',
    restaurantId: 'rest-1',
    restaurantName: 'Nawabi Dum Biryani House',
    restaurantImage: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=300&auto=format&fit=crop&q=80',
    restaurantAddress: 'Plot 42, 80 Feet Road, Koramangala',
    items: [
      {
        id: 'cart-prev-1',
        menuItemId: 'item-101',
        restaurantId: 'rest-1',
        restaurantName: 'Nawabi Dum Biryani House',
        name: 'Hyderabadi Chicken Dum Biryani',
        price: 299,
        vegType: 'non-veg',
        image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=300&auto=format&fit=crop&q=80',
        quantity: 2,
      },
      {
        id: 'cart-prev-2',
        menuItemId: 'item-106',
        restaurantId: 'rest-1',
        restaurantName: 'Nawabi Dum Biryani House',
        name: 'Shahi Tukda with Rabri',
        price: 149,
        vegType: 'veg',
        image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=300&auto=format&fit=crop&q=80',
        quantity: 1,
      },
    ],
    itemTotal: 747,
    deliveryFee: 0,
    taxes: 37,
    discount: 100,
    platformFee: 5,
    tip: 30,
    grandTotal: 719,
    status: 'delivered',
    createdAt: 'Yesterday, 8:45 PM',
    estimatedDeliveryTime: 'Delivered in 28 mins',
    deliveryAddress: SAMPLE_ADDRESSES[0],
    paymentMethod: 'UPI (Google Pay)',
    deliveryPartner: {
      name: 'Ramesh Kumar',
      phone: '+91 91234 56789',
      rating: 4.9,
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
      vehicleNumber: 'KA 01 EK 4920',
    },
  },
  {
    id: 'order-1002',
    orderNumber: 'ZK-87114',
    restaurantId: 'rest-3',
    restaurantName: 'Dosa Factory & South Express',
    restaurantImage: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=300&auto=format&fit=crop&q=80',
    restaurantAddress: 'Near Sony World Signal, Koramangala',
    items: [
      {
        id: 'cart-prev-3',
        menuItemId: 'item-301',
        restaurantId: 'rest-3',
        restaurantName: 'Dosa Factory & South Express',
        name: 'Ghee Roast Mysore Masala Dosa',
        price: 145,
        vegType: 'veg',
        image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=300&auto=format&fit=crop&q=80',
        quantity: 2,
      },
      {
        id: 'cart-prev-4',
        menuItemId: 'item-304',
        restaurantId: 'rest-3',
        restaurantName: 'Dosa Factory & South Express',
        name: 'Traditional South Indian Filter Coffee',
        price: 65,
        vegType: 'veg',
        image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=300&auto=format&fit=crop&q=80',
        quantity: 2,
      },
    ],
    itemTotal: 420,
    deliveryFee: 25,
    taxes: 21,
    discount: 50,
    platformFee: 5,
    tip: 20,
    grandTotal: 441,
    status: 'delivered',
    createdAt: '14 Aug 2026, 9:15 AM',
    estimatedDeliveryTime: 'Delivered in 22 mins',
    deliveryAddress: SAMPLE_ADDRESSES[0],
    paymentMethod: 'Credit Card (HDFC •••• 4242)',
    deliveryPartner: {
      name: 'Santosh Gowda',
      phone: '+91 98877 66554',
      rating: 4.8,
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
      vehicleNumber: 'KA 05 MN 1832',
    },
  },
];

export const DEFAULT_RESTAURANT_PROFILE: import('./types').RestaurantProfile = {
  name: 'gumti cafe',
  tagline: 'Coffee, chai, comfort food and plates made for good conversations.',
  phone: '+91 75067 52280',
  whatsappPhone: '917506752280',
  email: 'hello@ghuticafe.com',
  address: 'gumti cafe',
  locality: 'gumti cafe',
  city: 'Kolkata',
  pincode: '700001',
  fssaiNumber: '11223344556677',
  openingHours: '8:00 AM - 11:00 PM (Mon - Sun)',
  isOpen: true,
  bannerImage: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=1200&auto=format&fit=crop&q=80',
  logoImage: '/logo-gumti.png',
  upiId: 'ghuticafe@upi',
  upiPayeeName: 'gumti cafe',
  minOrderDelivery: 199,
  deliveryFee: 30,
  freeDeliveryThreshold: 499,
  estimatedDeliveryTime: '30-40 mins',
  estimatedPickupTime: '15-20 mins',
  serviceTaxPercentage: 5,
  enableDelivery: true,
  enablePickup: true,
  enableDineIn: true,
  socialInstagram: '@ghuticafe',
  googleMapsUrl: 'https://maps.google.com/?q=Ghuti+Cafe',
};

export const RESTAURANT_MENU_CATEGORIES = [
  'All Items',
  'Coffee',
  'Tea',
  'Burger',
  'Sandwich',
  'Pizzas',
  'Momo',
  'Noodles / Combos',
  'Small Bites',
  'Mutton Magic on Your Plate',
  'Soup',
  'Shake / Coolers',
];

// All menu items across catalog for fast retrieval & AI assistance
export const ALL_MENU_ITEMS: import('./types').MenuItem[] = RESTAURANTS.flatMap((r) => r.menu);

export const DEFAULT_CUSTOMERS: import('./types').CustomerRecord[] = [
  {
    id: 'cust-1',
    name: 'Indrajit Ghosh',
    phone: '+91 98765 43210',
    email: 'indrajit@example.com',
    address: 'Flat 402, Green Glen Layout, 100ft Road',
    area: 'Indiranagar',
    totalOrders: 6,
    totalSpent: 3420,
    lastOrderDate: 'Today, 2:15 PM',
    isVip: true,
    notes: 'Prefers extra spicy and green chutney',
  },
  {
    id: 'cust-2',
    name: 'Ananya Sharma',
    phone: '+91 98112 34567',
    email: 'ananya.s@example.com',
    address: 'Tower B, 12th Floor, Prestige Acropolis',
    area: 'Koramangala',
    totalOrders: 4,
    totalSpent: 2180,
    lastOrderDate: 'Yesterday, 8:30 PM',
    isVip: true,
    notes: 'Regular weekend dinner customer',
  },
  {
    id: 'cust-3',
    name: 'Vikramaditya Rao',
    phone: '+91 99008 87766',
    email: 'vikram.rao@example.com',
    address: 'Villa 14, Palm Meadows, Whitefield',
    area: 'Whitefield',
    totalOrders: 3,
    totalSpent: 1650,
    lastOrderDate: '16 Aug 2026',
    isVip: false,
    notes: 'Loves Murgh Dum Biryani',
  },
  {
    id: 'cust-4',
    name: 'Pooja Hegde',
    phone: '+91 97411 22334',
    email: 'pooja.h@example.com',
    address: '4th Cross, 14th Main, HSR Sector 2',
    area: 'HSR Layout',
    totalOrders: 2,
    totalSpent: 980,
    lastOrderDate: '14 Aug 2026',
    isVip: false,
    notes: 'Dine-in regular (Table 4)',
  },
  {
    id: 'cust-5',
    name: 'Siddharth Roy',
    phone: '+91 98220 99881',
    email: 'sid.roy@example.com',
    address: 'Apartment 203, Sobha Daisy, Bellandur',
    area: 'Bellandur',
    totalOrders: 1,
    totalSpent: 750,
    lastOrderDate: '12 Aug 2026',
    isVip: false,
  },
];

export const DEFAULT_ANNOUNCEMENT: import('./types').BannerAnnouncement = {
  enabled: true,
  text: '🎉 Chef Special: Flat 20% OFF on all royal biryanis and tandoor grills! Use code ZAIKA20 on checkout.',
  badge: 'FESTIVAL SPECIAL',
  linkText: 'Order Now',
  couponCode: 'ZAIKA20',
};

export const DEFAULT_TABLE_BOOKING_CONFIG: import('./types').TableBookingConfig = {
  enableBookings: true,
  requireEmail: false,
  showEmailField: true,
  showSeatingArea: true,
  showSpecialOccasion: true,
  showSpecialNotes: true,
  minGuests: 1,
  maxGuests: 10,
  timeSlots: [
    '08:30 AM',
    '09:30 AM',
    '10:30 AM',
    '11:30 AM',
    '12:30 PM',
    '01:30 PM',
    '02:30 PM',
    '04:00 PM',
    '05:30 PM',
    '06:30 PM',
    '07:30 PM',
    '08:30 PM',
    '09:30 PM',
    '10:00 PM',
  ],
  seatingOptions: [
    { id: 'indoor', label: 'Indoor AC Dining', icon: '❄️', desc: 'Cozy cafe ambience with curated soft music' },
    { id: 'outdoor', label: 'Outdoor Garden & Verandah', icon: '🌿', desc: 'Open air breeze & evening mood lighting' },
    { id: 'rooftop', label: 'Adda Corner / Lounge', icon: '✨', desc: 'Spacious group tables & comfortable couches' },
    { id: 'any', label: 'First Available Table', icon: '⚡', desc: 'Fastest seating upon arrival' },
  ],
  occasions: [
    { id: 'none', label: 'Casual Dine-in', icon: '🍽️' },
    { id: 'birthday', label: 'Birthday Celebration 🎂', icon: '🎉' },
    { id: 'anniversary', label: 'Anniversary 💖', icon: '🥂' },
    { id: 'date', label: 'Coffee Date ☕', icon: '🌹' },
    { id: 'family', label: 'Family Get-Together 👨‍👩‍👧‍👦', icon: '🥘' },
    { id: 'business', label: 'Work & Adda 💼', icon: '💻' },
  ],
  noticeHours: 1,
};

