import { MenuItem } from './types';

const images: Record<string, string> = {
    Coffee: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80',
    Tea: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=900&q=80',
    Burger: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=80',
    Sandwich: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=900&q=80',
    Pizzas: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=900&q=80',
    Momo: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=900&q=80',
    'Noodles / Combos': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=900&q=80',
    'Small Bites': 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=900&q=80',
    'Mutton Magic on Your Plate': 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=900&q=80',
    Soup: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=900&q=80',
    'Shake / Coolers': 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=80',
};

const ranged = (small: number, large: number) => [{
    id: 'size-small', name: `Regular - ₹${small}`, price: 0,
}, { id: 'size-large', name: `Large - ₹${large}`, price: large - small }];

const makeItem = (
    id: string,
    category: string,
    name: string,
    price: number,
    description = 'Freshly prepared to order with carefully selected ingredients.',
    vegType: MenuItem['vegType'] = 'veg',
    sizePrices?: [number, number],
): MenuItem => ({
    id: `ghuti-${id}`,
    restaurantId: 'my-restaurant',
    name,
    description,
    price,
    image: images[category],
    category,
    vegType,
    rating: 4.7,
    ratingCount: 120,
    isBestseller: ['Cappuccino', 'Cold Coffee', 'Classic Veg Cheesy Burger', 'Chicken Club Sandwich', 'Steamed Chicken Momo', 'Virgin Mojito', 'Mutton Kosha (2 pcs)'].includes(name),
    isSpicy: /chilli|pepper|peri peri|manchow|lollipop|drums|mutton/i.test(name),
    spiceLevel: /chilli|pepper|peri peri|manchow|lollipop|drums|mutton/i.test(name) ? 2 : 0,
    isAvailable: true,
    preparationTime: category === 'Coffee' || category === 'Tea' ? '5-10 mins' : '15-25 mins',
    customizationGroups: sizePrices ? [{ id: 'size', title: 'Choose Size', type: 'radio', options: ranged(...sizePrices) }] : undefined,
});

export const GHUTI_CAFE_MENU_VERSION = 2;

export const GHUTI_CAFE_MENU: MenuItem[] = [
    makeItem('coffee-1', 'Coffee', 'Cappuccino', 199, 'Velvety espresso, steamed milk and a delicate foam finish.'),
    makeItem('coffee-2', 'Coffee', 'Americano', 89, 'Rich espresso softened with hot water.'),
    makeItem('coffee-3', 'Coffee', 'Espresso', 89, 'A short, bold and aromatic coffee shot.'),
    makeItem('coffee-4', 'Coffee', 'Cold Coffee', 120, 'Chilled creamy coffee blended for a smooth café-style finish.'),
    makeItem('coffee-5', 'Coffee', 'Cafe Special Milk Coffee', 25, 'Comforting house milk coffee.', 'veg', [25, 30]),
    makeItem('coffee-6', 'Coffee', 'Cafe Special Black Coffee', 25, 'Strong, aromatic black coffee.', 'veg', [25, 30]),
    makeItem('tea-1', 'Tea', 'Darjeeling First Flush', 70),
    makeItem('tea-2', 'Tea', 'Darjeeling Second Flush', 70),
    makeItem('tea-3', 'Tea', 'Assam Tea', 70),
    makeItem('tea-4', 'Tea', 'Green Regular', 80),
    makeItem('tea-5', 'Tea', 'Green Tea Honey & Lemon', 110, 'Light green tea brightened with honey and lemon.'),
    makeItem('tea-6', 'Tea', 'Lemon Tea', 20, 'Bright and refreshing lemon tea.', 'veg', [20, 25]),
    makeItem('tea-7', 'Tea', 'Blue Ter', 110, 'A vibrant, floral and refreshing blue tea.'),
    makeItem('tea-8', 'Tea', 'Chocolate Chai', 40, 'House chai with a soft chocolate note.', 'veg', [40, 55]),
    makeItem('tea-9', 'Tea', 'Kesar Chai', 70, 'Fragrant chai infused with saffron.'),
    makeItem('tea-10', 'Tea', 'Hibiscus Tea', 70, 'Floral hibiscus tea with a naturally bright finish.'),
    makeItem('tea-11', 'Tea', 'Cafe Special Milk Tea', 20, 'House milk tea.', 'veg', [20, 25]),
    makeItem('tea-12', 'Tea', 'Cafe Special Black Tea', 15, 'House black tea.', 'veg', [15, 20]),
    makeItem('burger-1', 'Burger', 'Classic Veg Cheesy Burger', 150),
    makeItem('burger-2', 'Burger', 'Cheesy Aloo Tikia Burger', 170),
    makeItem('burger-3', 'Burger', 'Grilled Chicken Burger', 200, 'Grilled chicken patty with fresh toppings and cheese.', 'non-veg'),
    makeItem('burger-4', 'Burger', 'Crispy Chicken Burger', 200, 'Crispy chicken, fresh salad and house sauce.', 'non-veg'),
    makeItem('sandwich-1', 'Sandwich', 'Veg Sandwich', 100),
    makeItem('sandwich-2', 'Sandwich', 'Cheese Corn Sandwich', 120),
    makeItem('sandwich-3', 'Sandwich', 'Cheese Mushroom Sandwich', 120),
    makeItem('sandwich-4', 'Sandwich', 'Cheese Paneer Sandwich', 120),
    makeItem('sandwich-5', 'Sandwich', 'Veg Club Sandwich', 150),
    makeItem('sandwich-6', 'Sandwich', 'Cheese Egg Sandwich', 130, 'Cheesy egg sandwich with fresh vegetables.', 'egg'),
    makeItem('sandwich-7', 'Sandwich', 'Chicken Chilli Garlic Moya Sandwich', 150, 'Chicken sandwich with chilli garlic seasoning.', 'non-veg'),
    makeItem('sandwich-8', 'Sandwich', 'Egg Chicken Cheese Sandwich', 170, 'Egg, chicken and cheese layered in toasted bread.', 'non-veg'),
    makeItem('sandwich-9', 'Sandwich', 'Chicken Club Sandwich', 220, 'Triple-layer club sandwich with chicken, egg and fresh salad.', 'non-veg'),
    makeItem('pizza-1', 'Pizzas', 'B.BQ Chicken', 180, 'Smoky barbecue chicken with cheese.', 'non-veg'),
    makeItem('pizza-2', 'Pizzas', 'Peri Peri Chicken', 170, 'Cheesy pizza with spicy peri peri chicken.', 'non-veg'),
    makeItem('pizza-3', 'Pizzas', 'Peri Peri Pesto Veg', 120),
    makeItem('pizza-4', 'Pizzas', 'Paneer Veg Mushroom', 200),
    makeItem('pizza-5', 'Pizzas', 'Margarita Pizza', 160),
    makeItem('pizza-6', 'Pizzas', 'Chicken Pepperoni Pizza', 170, 'Classic cheese pizza with chicken pepperoni.', 'non-veg'),
    makeItem('momo-1', 'Momo', 'Steamed Vegetable Momo', 100),
    makeItem('momo-2', 'Momo', 'Fried Vegetable Momo', 100),
    makeItem('momo-3', 'Momo', 'Pan Fried Vegetable Momo', 120),
    makeItem('momo-4', 'Momo', 'Steamed Chicken Momo', 160, 'Juicy chicken momos steamed with aromatic seasoning.', 'non-veg'),
    makeItem('momo-5', 'Momo', 'Pan Fried Chicken Momo', 180, 'Pan-fried chicken momos with a crisp golden base.', 'non-veg'),
    makeItem('combo-1', 'Noodles / Combos', 'Veg Fried Rice/Noodles + Veg Manchurian + Cold Drink', 120),
    makeItem('combo-2', 'Noodles / Combos', 'Veg Fried Rice/Noodles + Chilli Paneer + Cold Drink', 130),
    makeItem('combo-3', 'Noodles / Combos', 'Veg Fried Rice/Noodles + Chilli Chicken (2 pcs) + Cold Drink', 150, 'A satisfying rice or noodle combo with chilli chicken.', 'non-veg'),
    makeItem('combo-4', 'Noodles / Combos', 'Chilli Chicken (2 pcs) + Cold Drink', 170, 'Chilli chicken with a chilled drink.', 'non-veg'),
    makeItem('combo-5', 'Noodles / Combos', 'Egg Chicken Fried Rice + Chicken (2 pcs) + Cold Drink', 200, 'Egg chicken fried rice with chicken and a cold drink.', 'non-veg'),
    makeItem('combo-6', 'Noodles / Combos', 'Mixed Fried Rice/Noodles + Chilli Chicken (2 pcs) + Cold Drink', 160, 'Mixed rice or noodles with chilli chicken.', 'non-veg'),
    makeItem('combo-7', 'Noodles / Combos', 'Veg Sandwich + French Fries + Coke', 190),
    makeItem('combo-8', 'Noodles / Combos', 'Egg Sandwich + French Fries + Coke', 160, 'Egg sandwich served with fries and Coke.', 'egg'),
    makeItem('combo-9', 'Noodles / Combos', 'Chicken Sandwich + French Fries + Coke', 180, 'Chicken sandwich served with fries and Coke.', 'non-veg'),
    makeItem('combo-10', 'Noodles / Combos', 'Veg Fried Rice/Noodles + Chilli Fish + Cold Drink', 170, 'Veg rice or noodles with chilli fish.', 'non-veg'),
    makeItem('bites-1', 'Small Bites', 'Chilli Paneer', 180),
    makeItem('bites-2', 'Small Bites', 'American Corn Pepper Salt (Veg)', 160),
    makeItem('bites-3', 'Small Bites', 'Stir Fry Crispy (Veg)', 180),
    makeItem('bites-4', 'Small Bites', 'Mushroom Pepper', 200),
    makeItem('bites-5', 'Small Bites', 'Crispy Chicken', 220, 'Crispy golden chicken bites with house dip.', 'non-veg'),
    makeItem('bites-6', 'Small Bites', 'B.B.Q Chicken (8 pcs)', 220, 'Eight pieces of smoky barbecue chicken.', 'non-veg'),
    makeItem('bites-7', 'Small Bites', 'Chicken Lollipop (6 pcs)', 110, 'Six crisp chicken lollipops with spicy glaze.', 'non-veg'),
    makeItem('bites-8', 'Small Bites', 'Drums of Heaven (6 pcs)', 180, 'Six fiery, crunchy chicken drumettes.', 'non-veg'),
    makeItem('bites-9', 'Small Bites', 'Chilli Garlic Pepper Chicken (8 pcs)', 200, 'Eight pieces of chilli garlic pepper chicken.', 'non-veg'),
    makeItem('mutton-1', 'Mutton Magic on Your Plate', 'Mutton Kosha (2 pcs)', 230, 'Slow-cooked Bengali-style mutton with rich caramelised spices.', 'non-veg'),
    makeItem('mutton-2', 'Mutton Magic on Your Plate', 'Mutton Curry (2 pcs)', 230, 'Tender mutton in a comforting house curry.', 'non-veg'),
    makeItem('mutton-3', 'Mutton Magic on Your Plate', 'Mutton Roganjosh (2 pcs)', 300, 'Aromatic mutton curry with warming spices.', 'non-veg'),
    makeItem('mutton-4', 'Mutton Magic on Your Plate', 'Mutton Rezala (2 pcs)', 350, 'Delicate creamy mutton rezala with fragrant spices.', 'non-veg'),
    makeItem('mutton-5', 'Mutton Magic on Your Plate', 'Special Mutton Jhol with Vegetable (2 pcs)', 300, 'House special mutton jhol with seasonal vegetables.', 'non-veg'),
    makeItem('soup-1', 'Soup', 'Veg Sweet Corn Soup', 130),
    makeItem('soup-2', 'Soup', 'Veg Manchow Soup', 130, 'Spiced vegetable soup topped with crisp noodles.'),
    makeItem('soup-3', 'Soup', 'Veg Hot & Sour Soup', 130),
    makeItem('soup-4', 'Soup', 'Cream of Broccoli', 225, 'Smooth creamy broccoli soup.'),
    makeItem('soup-5', 'Soup', 'Cream of Mushroom', 170, 'Silky mushroom soup with a deep earthy flavour.'),
    makeItem('soup-6', 'Soup', 'Chicken Sweet Corn Soup', 160, 'Comforting sweet corn soup with tender chicken.', 'non-veg'),
    makeItem('cooler-1', 'Shake / Coolers', 'Virgin Mojito', 140, 'Lime, mint and bubbles for a cool refreshing sip.'),
    makeItem('cooler-2', 'Shake / Coolers', 'Blue Lagoon', 130, 'Bright citrus cooler with a blue tropical twist.'),
    makeItem('cooler-3', 'Shake / Coolers', 'Tangy Orange', 130, 'Zesty orange cooler with a lively citrus finish.'),
    makeItem('cooler-4', 'Shake / Coolers', 'Mango Crush', 130, 'Thick, tropical mango cooler.'),
    makeItem('cooler-5', 'Shake / Coolers', 'Pineapple Crush', 130, 'Tropical pineapple cooler.'),
    makeItem('cooler-6', 'Shake / Coolers', 'Strawberry', 130, 'Sweet and creamy strawberry cooler.'),
];
